/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.44
 * Generated at: 2025-08-29 16:32:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.admin;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class add_002dcategory_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1756348887697L));
    _jspx_dependants.put("jar:file:/D:/SpringTools/workspace02/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/23110327/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c.tld", Long.valueOf(1664428278000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Thêm danh mục</title>\r\n");
      out.write("<style>\r\n");
      out.write("* {\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("	font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("	background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\r\n");
      out.write("	min-height: 100vh;\r\n");
      out.write("	padding: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container {\r\n");
      out.write("	max-width: 600px;\r\n");
      out.write("	margin: 50px auto;\r\n");
      out.write("	background: white;\r\n");
      out.write("	padding: 40px;\r\n");
      out.write("	border-radius: 15px;\r\n");
      out.write("	box-shadow: 0 20px 40px rgba(0, 0, 0, 0.1);\r\n");
      out.write("	backdrop-filter: blur(10px);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h1 {\r\n");
      out.write("	color: #333;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	margin-bottom: 40px;\r\n");
      out.write("	font-size: 2.2em;\r\n");
      out.write("	font-weight: 300;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-group {\r\n");
      out.write("	margin-bottom: 25px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("label {\r\n");
      out.write("	display: block;\r\n");
      out.write("	margin-bottom: 8px;\r\n");
      out.write("	font-weight: 600;\r\n");
      out.write("	color: #495057;\r\n");
      out.write("	font-size: 14px;\r\n");
      out.write("	text-transform: uppercase;\r\n");
      out.write("	letter-spacing: 0.5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=\"text\"], input[type=\"file\"] {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	padding: 15px;\r\n");
      out.write("	border: 2px solid #e9ecef;\r\n");
      out.write("	border-radius: 8px;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	transition: all 0.3s ease;\r\n");
      out.write("	background-color: #f8f9fa;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=\"text\"]:focus, input[type=\"file\"]:focus {\r\n");
      out.write("	border-color: #007bff;\r\n");
      out.write("	outline: none;\r\n");
      out.write("	box-shadow: 0 0 0 3px rgba(0, 123, 255, 0.1);\r\n");
      out.write("	background-color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=\"text\"]::placeholder {\r\n");
      out.write("	color: #adb5bd;\r\n");
      out.write("	font-style: italic;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".file-input-wrapper {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	overflow: hidden;\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".file-input-label {\r\n");
      out.write("	display: block;\r\n");
      out.write("	padding: 15px;\r\n");
      out.write("	background: linear-gradient(135deg, #6c757d 0%, #495057 100%);\r\n");
      out.write("	color: white;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	border-radius: 8px;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	transition: all 0.3s ease;\r\n");
      out.write("	font-weight: 500;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".file-input-label:hover {\r\n");
      out.write("	background: linear-gradient(135deg, #495057 0%, #343a40 100%);\r\n");
      out.write("	transform: translateY(-1px);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=\"file\"] {\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	left: -9999px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn {\r\n");
      out.write("	padding: 15px 25px;\r\n");
      out.write("	margin: 8px;\r\n");
      out.write("	border: none;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	border-radius: 8px;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	font-weight: 500;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	transition: all 0.3s ease;\r\n");
      out.write("	text-transform: uppercase;\r\n");
      out.write("	letter-spacing: 0.5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-primary {\r\n");
      out.write("	background: linear-gradient(135deg, #28a745 0%, #20c997 100%);\r\n");
      out.write("	color: white;\r\n");
      out.write("	box-shadow: 0 4px 15px rgba(40, 167, 69, 0.3);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-primary:hover {\r\n");
      out.write("	background: linear-gradient(135deg, #1e7e34 0%, #17a2b8 100%);\r\n");
      out.write("	transform: translateY(-2px);\r\n");
      out.write("	box-shadow: 0 8px 25px rgba(40, 167, 69, 0.4);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-secondary {\r\n");
      out.write("	background: linear-gradient(135deg, #6c757d 0%, #495057 100%);\r\n");
      out.write("	color: white;\r\n");
      out.write("	box-shadow: 0 4px 15px rgba(108, 117, 125, 0.3);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-secondary:hover {\r\n");
      out.write("	background: linear-gradient(135deg, #495057 0%, #343a40 100%);\r\n");
      out.write("	transform: translateY(-2px);\r\n");
      out.write("	box-shadow: 0 8px 25px rgba(108, 117, 125, 0.4);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button-group {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	margin-top: 40px;\r\n");
      out.write("	padding-top: 30px;\r\n");
      out.write("	border-top: 1px solid #e9ecef;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-info {\r\n");
      out.write("	background: linear-gradient(135deg, #cce5ff 0%, #e6f3ff 100%);\r\n");
      out.write("	padding: 15px;\r\n");
      out.write("	border-radius: 8px;\r\n");
      out.write("	margin-bottom: 30px;\r\n");
      out.write("	border-left: 4px solid #007bff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-info p {\r\n");
      out.write("	color: #495057;\r\n");
      out.write("	font-size: 14px;\r\n");
      out.write("	margin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media ( max-width : 768px) {\r\n");
      out.write("	.container {\r\n");
      out.write("		margin: 20px auto;\r\n");
      out.write("		padding: 25px;\r\n");
      out.write("	}\r\n");
      out.write("	h1 {\r\n");
      out.write("		font-size: 1.8em;\r\n");
      out.write("	}\r\n");
      out.write("	.btn {\r\n");
      out.write("		display: block;\r\n");
      out.write("		width: 100%;\r\n");
      out.write("		margin: 10px 0;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<h1>➕ Thêm danh mục mới</h1>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<form role=\"form\" action=\"add\" method=\"post\"\r\n");
      out.write("			enctype=\"multipart/form-data\">\r\n");
      out.write("			<div class=\"form-group\">\r\n");
      out.write("				<label for=\"categoryName\">📝 Tên danh mục:</label> <input\r\n");
      out.write("					type=\"text\" id=\"categoryName\" class=\"form-control\"\r\n");
      out.write("					placeholder=\"......\" name=\"name\"\r\n");
      out.write("					required maxlength=\"100\" />\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"form-group\">\r\n");
      out.write("				<label for=\"categoryIcon\">🖼️ Ảnh đại diện:</label>\r\n");
      out.write("				<div class=\"file-input-wrapper\">\r\n");
      out.write("					<input type=\"file\" id=\"categoryIcon\" name=\"icon\" accept=\"image/*\"\r\n");
      out.write("						onchange=\"updateFileName(this)\" /> <label for=\"categoryIcon\"\r\n");
      out.write("						class=\"file-input-label\" id=\"fileLabel\"> 📁 Chọn hình ảnh\r\n");
      out.write("						(PNG, JPG, GIF...) </label>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"button-group\">\r\n");
      out.write("				<button type=\"submit\" class=\"btn btn-primary\">💾 Thêm danh\r\n");
      out.write("					mục</button>\r\n");
      out.write("				<button type=\"reset\" class=\"btn btn-secondary\"\r\n");
      out.write("					onclick=\"resetFileLabel()\">🔄 Reset</button>\r\n");
      out.write("				<a href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("					class=\"btn btn-secondary\">🔙 Quay lại danh sách</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("		function updateFileName(input) {\r\n");
      out.write("			const label = document.getElementById('fileLabel');\r\n");
      out.write("			if (input.files && input.files[0]) {\r\n");
      out.write("				label.textContent = '📁 Đã chọn: ' + input.files[0].name;\r\n");
      out.write("				label.style.background = 'linear-gradient(135deg, #28a745 0%, #20c997 100%)';\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function resetFileLabel() {\r\n");
      out.write("			const label = document.getElementById('fileLabel');\r\n");
      out.write("			label.textContent = '📁 Chọn hình ảnh (PNG, JPG, GIF...)';\r\n");
      out.write("			label.style.background = 'linear-gradient(135deg, #6c757d 0%, #495057 100%)';\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		// Form validation\r\n");
      out.write("		document.querySelector('form').addEventListener('submit', function(e) {\r\n");
      out.write("			const nameInput = document.getElementById('categoryName');\r\n");
      out.write("			if (nameInput.value.trim().length < 2) {\r\n");
      out.write("				alert('⚠️ Tên danh mục phải có ít nhất 2 ký tự!');\r\n");
      out.write("				e.preventDefault();\r\n");
      out.write("				nameInput.focus();\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f0.setParent(null);
    // /views/admin/add-category.jsp(211,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f0.setValue("/admin/category/list");
    int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
    if (_jspx_th_c_005furl_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
    return false;
  }
}
